---
extends:
  - airbnb
  - prettier

parser: babel-eslint

plugins:
  - prettier

env:
  node: true
  jest: true

rules:
  prettier/prettier: "error"
  no-tabs: 'off'
  indent:
    - error
    - tab
    - SwitchCase: 1
  comma-dangle: 'off'
